version: 0.0
os: linux
#files:
#  - source: Config/config.txt
#    destination: /webapps/Config
#  - source: source
#    destination: /webapps/myApp
hooks:
  BeforeInstall:
    - location: Scripts/install.sh
  AfterInstall:
    - location: Scripts/version.sh
      timeout: 180
  ApplicationStart:
    - location: Scripts/node.sh
      timeout: 3600
